version: '3.8'

services:
  gam-api:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - GAM_ENV=production
    volumes:
      - gam-data:/app/data
      - gam-results:/app/results
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - gam-network

  gam-dashboard:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.dashboard
    ports:
      - "8501:8501"
    depends_on:
      gam-api:
        condition: service_healthy
    environment:
      - GAM_ENV=production
      - GAM_API_URL=http://gam-api:8000
    volumes:
      - gam-results:/app/results
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - gam-network

volumes:
  gam-data:
    driver: local
  gam-results:
    driver: local

networks:
  gam-network:
    driver: bridge