

services:
  api:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.api
    ports:
      - "8000:8000"
    expose:
      - "8000"
    environment:
      - GAM_ENV=production
      - PYTHONUNBUFFERED=1
    volumes:
      - ../../../data:/app/data
      - gam-results:/app/results
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/openapi.json"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - gam-network

  dashboard:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.dashboard
    ports:
      - "8501:8501"
    expose:
      - "8501"
    depends_on:
      api:
        condition: service_healthy
    environment:
      - GAM_ENV=production
      - GAM_API_URL=http://api:8000
      - CESIUM_TOKEN=${CESIUM_TOKEN}
      - MPLBACKEND=Agg
      - PYTHONUNBUFFERED=1
    volumes:
      - ../../../data:/app/data
      - gam-results:/app/results
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - gam-network

  proxy:
    image: nginx:alpine
    depends_on:
      - api
      - dashboard
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - gam-network

volumes:
  gam-data:
    driver: local
  gam-results:
    driver: local

networks:
  gam-network:
    driver: bridge