# Prometheus scrape configuration for GeoAnomalyMapper (GAM)
# Include in prometheus.yml: rule_files: [gam-rules.yml] scrape_configs: [gam]
# Targets GAM /metrics endpoint for custom metrics: ingestion_rate, modeling_duration_seconds, anomaly_count_total, etc.
# Usage: curl http://gam-service:8000/metrics

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'gam'
    metrics_path: '/metrics'
    scheme: http
    static_configs:
      - targets: ['gam-service.gam-system.svc.cluster.local:8000']  # K8s service discovery; adjust for Docker/VM
        labels:
          environment: production
          service: geoanomalymapper
          namespace: gam-system
          instance: gam-01
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__meta_kubernetes_service_name]
        target_label: service_name
        regex: gam-service
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
        regex: gam-system
      - source_labels: [__meta_kubernetes_pod_container_port_number]
        action: keep
        regex: 8000
    # Basic auth if API secured
    # basic_auth:
    #   username: ${PROMETHEUS_USER}
    #   password: ${PROMETHEUS_PASS}
    # TLS if HTTPS
    # scheme: https
    # tls_config:
    #   insecure_skip_verify: true
    #   ca_file: /etc/prometheus/ca.pem

  - job_name: 'gam-cache-redis'
    static_configs:
      - targets: ['redis.gam-system.svc.cluster.local:6379']
        labels:
          environment: production
          service: redis-cache
          namespace: gam-system
    metrics_path: '/metrics'
    scheme: http
    scrape_interval: 30s

# Alerting rules (separate file gam-rules.yml)
rule_files:
  - 'gam-rules.yml'

# Example rules for gam-rules.yml:
# groups:
# - name: gam.rules
#   rules:
#   - alert: GAMHighErrorRate
#     expr: rate(gam_errors_total[5m]) > 0.05
#     for: 2m
#     labels:
#       severity: warning
#     annotations:
#       summary: "High error rate in GAM pipeline"
#       description: "Error rate is {{ $value }} for the last 5 minutes"
#   - alert: GAMIngestionSlow
#     expr: gam_ingestion_duration_seconds > 300
#     for: 1m
#     labels:
#       severity: critical
#     annotations:
#       summary: "Slow ingestion in GAM"
#       description: "Ingestion taking longer than 5 minutes: {{ $value }}s"