# keys: urls, expected_filename, target_dir, update, auth, checksum
# update: static|periodic|monthly|daily|regenerate
# auth placeholders: ${ESA_USERNAME}, ${ESA_PASSWORD}, ${EARTHDATA_USER}, ${EARTHDATA_PASS}

# Sentinel-1 GRD and SLC datasets for raw product downloads via sentinelsat
# Authentication via ESA_USERNAME and ESA_PASSWORD environment variables
# Downloads individual ZIP products named by product ID to target_dir
# Manifest JSON written alongside with product details
# Params provide defaults for query filters; orbit_direction null means any

sentinel1_grd:
  urls:
    - "https://scihub.copernicus.eu/dhus"   # primary Copernicus Open Access Hub
    - "https://apihub.copernicus.eu/apihub" # legacy fallback
  expected_filename: "S1_GRDSentinel1_grd_{start:%Y%m%d}-{end:%Y%m%d}.zip"  # unused for per-product; for manifest if needed
  target_dir: "data/raw/sentinel1/grd"
  update: "daily"
  params:
    producttype: "GRD"
    polarization: ["VV", "VH"]
    orbit_direction: null
    max_results: 50

sentinel1_slc:
  urls:
    - "https://scihub.copernicus.eu/dhus"   # primary
  expected_filename: "S1_SLCSentinel1_slc_{start:%Y%m%d}-{end:%Y%m%d}.zip"  # unused for per-product
  target_dir: "data/raw/sentinel1/slc"
  update: "daily"
  params:
    producttype: "SLC"
    polarization: ["VV", "VH"]
    orbit_direction: null
    max_results: 25

gravity:
  base_url: "https://mrdata.usgs.gov/services/gravity?bbox={bbox}&format=geojson"
  client_type: "requests"
  default_params: {}
  auth: null
  # NOTE: This entry relies on base_url and default_params for fetching data,
  # not a direct file URL. The loader will need to handle this configuration.

magnetic:
  base_url: "https://mrdata.usgs.gov/services/magnetic?bbox={bbox}&format=geojson"
  client_type: "requests"
  default_params: {}
  auth: null
  # NOTE: Similar to gravity, relies on base_url.

seismic:
  urls: ["IRIS", "USGS"]
  expected_filename: "events_{start:%Y%m%d}-{end:%Y%m%d}.jsonl"
  target_dir: "data/raw/seismic"
  update: "daily"
  default_start_days: 30
  default_minmagnitude: 0.0
  # Legacy params for compatibility (ignored in new impl)
  client_type: "obspy"
  fdsn_server: "IRIS"
  default_params:
    network: "*"
    station: "*"
    location: "*"
    channel: "BH?"
    starttime: "2020-01-01"
    endtime: "2025-09-22"
  auth: null

insar:
  source: "esa_copernicus"
  api_url: "https://apihub.copernicus.eu/apihub"
  product_type: "GRD"
  polarisation: "VV"
  # Authentication: Set ESA_USERNAME and ESA_PASSWORD environment variables

emag2_v3:
  description: NOAA NCEI EMAG2 v3 global magnetic anomaly grid
  urls:
    - "https://www.ngdc.noaa.gov/geomag/data/EMAG2/EMAG2_V3_SeaLevel_DataTiff.tif"
    - "https://www.ngdc.noaa.gov/geomag/data/EMAG2/EMAG2_V3_UpCont_DataTiff.tif"
  expected_filename: EMAG2_V3_SeaLevel_DataTiff.tif
  format: geotiff
  target_dir: ./data/raw/emag2
  license: Public Domain (NOAA/NCEI)
  citation: "Maus, S., et al. (2009). EMAG2: A new era in exploration of the global magnetic field. G3, 10(6). Updated to v3 (2020)."
  attribution: "Data provided by NOAA National Centers for Environmental Information (NCEI)"
  notes: "2 arc-min global magnetic anomaly in nT. Sea-level grid preferred; UpCont is upward-continued."
  update: static
  sha256: ""

egm2008_gravity: # Consolidated key for EGM2008 gravity from both sources
  description: EGM2008 global gravity anomaly, including coefficients and pre-gridded data. Derived from GOCE/EGM2008.
  urls:
    - "https://download.icgem.gfz-potsdam.de/GravityModels/EGM2008.gfc" # Coefficients from GeoAnomalyMapper/data_sources.yaml
    - "https://www.ngdc.noaa.gov/mgg/global/relief/ETOPO1/data/bathymetry/egm2008/Gravity_Anomaly_World.tif" # GeoTIFF from GeoAnomalyMapper/data_sources.yaml
    - "https://download.icgem.gfz-potsdam.de/GravityModels/egm2008_anomaly_5min.tif.gz" # GeoTIFF (.gz) from data_sources.yaml
  expected_filename: egm2008_anomaly_5min.tif # Default from the .tif.gz file
  target_dir: ./data/raw/gravity
  license: Public Domain (NASA/EGM2008, ICGEM/NASA/NGA)
  citation: "Pavlis, N. K., et al. (2012). The Development and Evaluation of the Earth Gravitational Model 2008 (EGM2008). Journal of Geophysical Research: Solid Earth, 117(B4)."
  attribution: "Data derived from EGM2008 model by NGA and NASA; gridded data by GFZ/ICGEM"
  notes: "Includes spherical harmonic coefficients and 5 arc-min global free-air gravity anomaly (mGal). .tif.gz file needs uncompression."
  update: static
  sha256: ""

harmonics_egm2008:
  urls:
    - "https://download.icgem.gfz-potsdam.de/GravityModels/EGM2008/EGM2008.gfc"
  expected_filename: "EGM2008.gfc"
  target_dir: "data/raw/harmonics"
  update: "static"
  params:
    degree: 360
    field: "geoid"              # choices: "geoid", "gravity_anomaly"
    spacing_arcmin: 5
    tide_system: "tide_free"    # optional passthrough if needed

harmonics_chaos:
  urls:
    - "https://www.space.dtu.dk/multidata/set-5/CHAOS-6/CHAOS-6-x11.gfc"  # Example CHAOS gravity .gfc; adjust to latest
  expected_filename: "CHAOS.gfc"
  target_dir: "data/raw/harmonics"
  update: "periodic"
  params:
    degree: 110
    field: "gravity_anomaly"   # Gravity for now; magnetic not implemented
    spacing_arcmin: 10